name: Build and push on release (new tag)

on:
  push:
    tags:
      - '*'

# Following is for testing only:
#on:
#  pull_request:
#    branches:
#      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # expected format of the new git tag: v1.2.3
    - name: Get tag
      id: get_tag
      # TODO: use GIT TAG!!! run: echo ::set-env name=GIT_TAG::${GITHUB_REF#refs/tags/}
      run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF#refs/tags/} | sed -e 's/^v//g')
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: |
        git config user.name 'GitHub action executed on release'
        git config user.email 'github@users.noreply.github.com'
    - run: yarn install
    - run: yarn publish --new-version ${{ env.VERSION }} --no-git-tag-version 
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Autogenerated new version ${{ env.VERSION }}
        base: master
        commit-message: Add dummy file
        committer: GitHub action executed on release <noreply@github.com>
        author: GitHub action executed on release <noreply@github.com>


